import { combineReducers } from 'redux';
import {
  checktradPWD,
  getAuthRequest,
  getAuthenOnoff,
  getAuthenQuota,
  getToken,
  getUpLoadFaceAuth,
  getUpLoadImgAuth,
  getUpLoadSaveAuth,
  pwdComfireData,
  pwdResetData,
  registerConfirmData,
  registerData,
  userAuthInfo,
  userInfo,
} from './auth';
import { bannerList, baseAuthData, capitalCodeData, capitalInitData, capitalResetData, compareVersion, emergentNotice } from './base';
import {
  ReceiveaddressData,
  currencyDefaultData,
  getAllCloudWalletType,
  getCloudWalletAssets,
  getCloudWalletCarry,
  getCloudWalletCash,
  getCloudWalletType,
  getViewWallet,
  getWalletTransfer,
  getWalletType,
  localCollection,
  searchWalletType,
} from './wallet';
import { appConfig } from './base-config';
import { klineHistory } from './kline';
import {
  collectionList,
  collectionListCallBack,
  createEntrustOrderReply,
  increaseTopReply,
  klinePush,
  marketInfo,
  marketListInfo,
  orderBook,
  paymentCurrencys,
  revokeEntrustOrderReply,
  turnOverRecord,
  turnoverrecordAdd,
  userAvailablefunds,
  userEntrustOrders,
} from './websocket';
import { loginMode } from './login-mode';
import { closeGoogleData, googleAuthData, googleMessCode, googleSecret, isGoogleOpen } from './google-auth';
import { entrustDeal, entrustDetail, entrustHistory } from './entrust';

import { chenkBbLog } from './transfer';
import { chenkRuleLog } from './findloglist';
export default combineReducers({
  userInfo,
  compareVersion,
  emergentNotice,
  getWalletType,
  searchWalletType,
  collectionList,
  localCollection,
  appConfig,
  klineHistory,
  getToken,
  getAuthenQuota,
  // assignmentLocalCollection,
  bannerList,
  //websocket start
  marketInfo,
  marketListInfo,
  collectionListCallBack,
  getAuthenOnoff,
  orderBook,
  turnOverRecord,
  paymentCurrencys,
  klinePush,
  userEntrustOrders,
  userAvailablefunds,
  createEntrustOrderReply,
  increaseTopReply,
  revokeEntrustOrderReply,
  turnoverrecordAdd,
  //websocket end
  loginMode,
  registerData,
  pwdResetData,
  capitalResetData,
  capitalInitData,
  getAuthRequest,
  userAuthInfo,
  getUpLoadImgAuth,
  getUpLoadFaceAuth,
  getUpLoadSaveAuth,
  googleAuthData,
  isGoogleOpen,
  registerConfirmData,
  pwdComfireData,
  capitalCodeData,
  googleMessCode,
  googleAuthData,
  googleSecret,
  closeGoogleData,
  getViewWallet,
  getWalletTransfer,
  getCloudWalletAssets,
  getCloudWalletType,
  getAllCloudWalletType,
  getCloudWalletCarry,
  getCloudWalletCash,
  currencyDefaultData,
  ReceiveaddressData,
  entrustHistory,
  entrustDeal,
  entrustDetail,
  chenkBbLog,
  chenkRuleLog,
  baseAuthData,
  checktradPWD,
});
